import type { Metadata } from "next";
import "./globals.css";
import { Poppins, Plus_Jakarta_Sans } from 'next/font/google'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500'],
  display: 'swap',
})

const PlusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['400', '500'],
  display: 'swap',
  variable: '--font-plus-jakarta-sans',
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={`${PlusJakartaSans.variable}`}>
      <body className={`${poppins.className}`}>
        {children}
      </body>
    </html>
  );
}
